# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Crohn's Diary CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install WASM tools
      run: dotnet workload install wasm-tools

    - name: Publish App artifact
      uses: actions/upload-artifact@v4
      with:
        name: Deployment
        path: ./CrohnsDiary.Deploy

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish App
      run: dotnet publish ./CrohnsDiary.App/CrohnsDiary.App.csproj --no-build -o ./CrohnsDiary.App/publish
    - name: Publish App artifact
      uses: actions/upload-artifact@v4
      with:
        name: App
        path: ./CrohnsDiary.App/publish
  
  dev:
    runs-on: ubuntu-latest
    needs: build
    environment: development
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: actions/download-artifact@v4
        with:
          name: Deployment
          path: ./deploy
      - name: Restore dependencies
        run: dotnet restore ./deploy/CrohnsDiary.Deploy.csproj
      - name: Build
        run: dotnet build ./deploy/CrohnsDiary.Deploy.csproj -c Release --no-restore

      - uses: actions/download-artifact@v4
        with:
          name: App
          path: ./app
  
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

      - uses: pulumi/actions@v3
        with:
          command: up
          work-dir: ./deploy
          cloud-url: azblob://stacks?storage_account=stnbgpulumi
          stack-name: dev
          refresh: true
