# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Crohn's Diary CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    - name: Install WASM tools
      run: dotnet workload install wasm-tools

    - name: Publish Deployment artifact
      uses: actions/upload-artifact@v7
      with:
        name: Deployment
        path: ./CrohnsDiary.Deploy

    - name: Modify Imprint.md
      shell: pwsh
      env:
        content: ${{ vars.IMPRINT }}
      run: |
        Set-Content -Path ./CrohnsDiary.App/wwwroot/Imprint.md -Value "$env:content"

    - name: Modify Imprint.de.md
      shell: pwsh
      env:
        content: ${{ vars.IMPRINT_DE }}
      run: |
        Set-Content -Path ./CrohnsDiary.App/wwwroot/Imprint.de.md -Value "$env:content"

    - name: Modify Dataprotection.md
      shell: pwsh
      env:
        content: ${{ vars.DATA_PROTECTION }}
      run: |
        Set-Content -Path ./CrohnsDiary.App/wwwroot/Dataprotection.md -Value "$env:content"

    - name: Modify Dataprotection.de.md
      shell: pwsh
      env:
        content: ${{ vars.DATA_PROTECTION_DE }}
      run: |
        Set-Content -Path ./CrohnsDiary.App/wwwroot/Dataprotection.de.md -Value "$env:content"

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish App
      run: dotnet publish ./CrohnsDiary.App/CrohnsDiary.App.csproj --no-build -o ./CrohnsDiary.App/publish
    - name: Publish App artifact
      uses: actions/upload-artifact@v7
      with:
        name: App
        path: ./CrohnsDiary.App/publish

  dev:
    needs: build
    uses: ./.github/workflows/deploy-environment.yml
    with:
      stack-name: dev
      environment: development
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}

  prod:
    needs: dev
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/deploy-environment.yml
    with:
      stack-name: prod
      environment: production
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
