# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Crohn's Diary CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install WASM tools
      run: dotnet workload install wasm-tools

    - name: Publish Deployment artifact
      uses: actions/upload-artifact@v4
      with:
        name: Deployment
        path: ./CrohnsDiary.Deploy

    - name: Modify Imprint.md
      shell: pwsh
      env:
        content: ${{ vars.IMPRINT }}
      run: |
        Set-Content -Path ./CrohnsDiary.App/wwwroot/Imprint.md -Value "$env:content"

    - name: Modify Imprint.de.md
      shell: pwsh
      env:
        content: ${{ vars.IMPRINT_DE }}
      run: |
        Set-Content -Path ./CrohnsDiary.App/wwwroot/Imprint.de.md -Value "$env:content"

    - name: Modify Dataprotection.md
      shell: pwsh
      env:
        content: ${{ vars.DATA_PROTECTION }}
      run: |
        Set-Content -Path ./CrohnsDiary.App/wwwroot/Dataprotection.md -Value "$env:content"

    - name: Modify Dataprotection.de.md
      shell: pwsh
      env:
        content: ${{ vars.DATA_PROTECTION_DE }}
      run: |
        Set-Content -Path ./CrohnsDiary.App/wwwroot/Dataprotection.de.md -Value "$env:content"

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish App
      run: dotnet publish ./CrohnsDiary.App/CrohnsDiary.App.csproj --no-build -o ./CrohnsDiary.App/publish
    - name: Publish App artifact
      uses: actions/upload-artifact@v4
      with:
        name: App
        path: ./CrohnsDiary.App/publish

  dev:
    runs-on: ubuntu-latest
    needs: build
    environment: development
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: actions/download-artifact@v4
        with:
          name: Deployment
          path: ./deploy
      - name: Restore dependencies
        run: dotnet restore ./deploy/CrohnsDiary.Deploy.csproj
      - name: Build
        run: dotnet build ./deploy/CrohnsDiary.Deploy.csproj -c Release --no-restore

      - name: Download App
        uses: actions/download-artifact@v4
        with:
          name: App
          path: ./app

      # - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Azure Resources
        uses: pulumi/actions@v3
        with:
          command: up
          work-dir: ./deploy
          cloud-url: azblob://stacks?storage_account=stnbgpulumi
          stack-name: dev
          refresh: true
          config-map: "{ path: { value: '../app/wwwroot'} }"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_LOCATION_NAME: westeurope
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

  prod:
    runs-on: ubuntu-latest
    needs: dev
    environment: production
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: actions/download-artifact@v4
        with:
          name: Deployment
          path: ./deploy
      - name: Restore dependencies
        run: dotnet restore ./deploy/CrohnsDiary.Deploy.csproj
      - name: Build
        run: dotnet build ./deploy/CrohnsDiary.Deploy.csproj -c Release --no-restore

      - name: Download App
        uses: actions/download-artifact@v4
        with:
          name: App
          path: ./app

      # - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Azure Resources
        uses: pulumi/actions@v3
        with:
          command: up
          work-dir: ./deploy
          cloud-url: azblob://stacks?storage_account=stnbgpulumi
          stack-name: prod
          refresh: true
          config-map: "{ path: { value: '../app/wwwroot'} }"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_LOCATION_NAME: westeurope
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
